version: '3.8'
services:


  chat-frontend:
    build: 
      context: ../../
      dockerfile: docker/dev/Dockerfile
      args:
        VITE_SOCKET_URL: http://127.0.0.1
    container_name: dowellchat-frontend
    ports:
      - 80:80
    volumes:
      - .:/usr/src/app
      - ../../nginx/dev/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      VITE_SOCKET_URL: http://127.0.0.1
    restart: always
    networks:
      - webnet


networks:
    webnet:
        external: true
