version: '3.8'
services:

  100116q-frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        VITE_BACKEND_URL: http://100116q-backend:8000/
    container_name: 100116q-frontend
    ports:
      - 454:443
    volumes:
      - ./frontend:/usr/src/app
    environment:
      VITE_BACKEND_URL: http://100116q-backend:8000
    restart: always
    networks:
      - queue-net

  100116q-backend:
    build:
      context: ./backend
    container_name: 100116q-backend
    restart: always
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8008:8000"
    expose:
      - 8000
    volumes:
      - ./backend:/usr/src/app
    networks:
      - queue-net

  100116q-nginx:
    build: 
      context: ./nginx
      dockerfile: dev/Dockerfile
    container_name: 100116q-nginx
    ports:
      - 80:80
    volumes:
      - ./nginx:/usr/src/app
      - ./nginx/dev/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
    networks:
      - queue-net
    depends_on:
      - 100116q-backend
      - 100116q-frontend

networks:
  queue-net:
    external: true
