version: '3.8'
services:


  100116q-frontend:
    build: 
      context: ../../
      dockerfile: docker/prod/Dockerfile
      args:
        VITE_BACKEND_URL: http://100116q-backend:8000/
    container_name: 100116q-frontend
    ports:
      - 87:80
      - 454:443
    volumes:
      - .:/usr/src/app
      - ../../nginx/prod/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/www.q.uxlivinglab.online/fullchain.pem:/etc/letsencrypt/live/www.q.uxlivinglab.online/fullchain.pem:ro
      - /etc/letsencrypt/live/www.q.uxlivinglab.online/privkey.pem:/etc/letsencrypt/live/www.q.uxlivinglab.online/privkey.pem:ro
    environment:
      VITE_BACKEND_URL: http://100116q-backend:8000
    restart: always
    networks:
      - queue-net


networks:
    queue-net:
        external: true
