name: Deploy to Server

on:
  push:
    branches:
      - frontend  # Set this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    # If we ever change to passwordless login
    # - name: Set up SSH
    #   uses: webfactory/ssh-agent@v0.5.3
    #   with:
    #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Install sshpass
      run: sudo apt-get install -y sshpass


    - name: Deploy to Server
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no root@67.217.58.6 << 'EOF'
          cd /home/100116q-frontend
          git pull origin frontend
          docker-compose up -d --build
        EOF
